<a href="https://colab.research.google.com/github/dhyun16/ESAA/blob/main/ESAA_%EA%B9%80%EB%91%90%ED%98%84_Week1_%ED%95%84%EC%82%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01 파이썬 기반의 머신러닝과 생태계 이해
## 1.3 넘파이



### 넘파이 ndarray 개요

In [1]:
import numpy as np

넘파이의 기반 데이터 타입 **ndarray**  
+ 다차원(Multi-dimension) 배열 생성, 연산 수행
+ ```array()```함수는 파이썬의 리스트와 같은 다양한 인자를 입력받아 ndarray로 변환
+ ndarray 배열의 ```shape```변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지며 ndarray 배열의 차원까지 알  수 있음

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


```ndarray.shape``` ndarray의 차원과 크기를 튜플(tuple)형태로 나타냄  
+ *ex)* [1,2,3]의 shape: (3,) **-->** 1차원 array로, 3개의 데이터를 가짐
+ *ex)* [[1,2,3],[2,3,4]]의 shape: (2,3) *-->* 2차원 array로, 2개의 row와 3개의 column으로 구성  
+ *ex)* [[1,2,3]]의 shape: (1,3) *-->* 2차원 array로, 1개의 row와 3개의 column으로 구성  


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,
                                                           array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


### ndarray의 데이터 타입

+ ndarray내의 데이터 값은 숫자 값, 문자열 값, 불 값 등 모두 가능  
+ ndarray내의 데이터 타입은 그 연산의 특성상 **같은 데이터 타입**만 가능(리스트는 서로 다른 데이터 타입 가질 수 있음)  
+ ndarray내의 데이터 타입은 ```dtype```속성으로 확인

In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


만약 다른 데이터 유형이 섞여있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용

In [5]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


int형이 유니코드 문자열 값으로 변환  
int가 float64형으로 변환

ndarray 내 데이터값의 타입 변경 ```astype```메서드

In [6]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 =  array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones
```arange()```
+ array를 range()로 표현.
+ 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환


In [7]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


+ default 함수 인자는 stop 값이며, 0부터 stop 값인 10에서 -1을 더한 9까지의 연속 숫자값으로 구성된 1차원 ndarray를 만듦

```zeros()```
+ 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환

```ones()```
+ 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환

In [8]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

```reshape()```메서드
+ ndarray를 특정 차원 및 크기로 변환

In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = np.arange(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [2 3 4]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

-1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환

In [11]:
arrayl = np.arange(10)
print(array1)
array2 = arrayl.reshape(-1, 5)
print('array2 shape:', array2.shape)
arrays = arrayl.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

```reshape(—1,1)``` 원본 ndarray가 어떤
형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장

In [13]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1 차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

1. 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됩니다.  
2. 슬라이싱(Slicing): 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식입니다. ‘:’ 기호 사이에 시작 인덱스와
종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환합니다. 예를 들어
1:5라고 하면 시작 인덱스 1과 종료 인덱스 4까지에 해당하는 ndarray를 반환합니다.
3. 팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이
터의 ndarray를 반환합니다.
4. 불린 인덱싱(Boolean Indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True
에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환합니다.

### 단일 값 추출

In [14]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 arrayl[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


```array1[2]```의 타입은 ndarray 타입이 아닌 ndarray 내의 데이터값을 의미  


인덱스 -1은 맨 뒤
의 데이터값, -2는 맨 뒤에서 두 번째에 있는 데이터값

In [15]:
print('맨 뒤의 값:', array1[-1], ' 맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8


In [16]:
array1[0] = 9
array1[8] = 0
print('array1: ', array1)

array1:  [9 2 3 4 5 6 7 8 0]


In [17]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=O) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=O) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


정확한 표현으로는 넘파이의 다차원 ndarray는 row, column 형식이 아닌 axis 구분을 가짐(axis0, axis1, axis2..)

### 슬라이싱
+ ‘:’ 기호를 이용
+ 단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입  
+ ‘:’ 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1의 위치에 있는 데이터의 ndarray 를 반환

In [18]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


1. ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주합니다.
2. ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주합니다.
3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주합니다.

In [19]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


2차원 ndarray

In [20]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print ('array 2d :\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array 2d :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환  
3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환

In [21]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱
팬시 인덱싱(Fancy Indexing)은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환

In [22]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] => ',array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] =>  [3, 6]
array2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱
불린 인덱싱은 ndarray의 인덱스를 지정하는 [ ] 내에 조건문을 그대로 기재

In [23]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array 1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array 1d > 5 불린 인덱싱 결과 값 :', array3)

array 1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [24]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

1. 5 보다 큰 데이터가 있는 위치는True 값이, 그렇지 않는 경우는 False 값이 반환됨  
2. 조건으로 반환된 이 ndarray 객체를 인덱싱을 지정하는 [ ] 내에 입력하면 False 값은 무시하고 True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환

In [25]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [26]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


+ Step 1: arrayld〉5와 같이 ndarray의 필터링 조건을 [ ] 안에 기재
+ Step 2: False 값은 무시하고 True 값에 해당하는 인덱스값만 저장（유의해야 할 사항은 True값 자체인 1을 저장하는 것
이 아니라 True값을 가진 인덱스를 저장한다는 것입니다）
+ Step 3:  저장된 인덱스 데이터 세트로 ndarray 조회

### 행렬의 정렬 - sort()와 argsort()
#### 행렬 정렬
+ ```np.sort()```
  * 넘파이에서 ```sort()```를 호출하는 방식
  * 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
  * 기본적으로 오름차순으로 행렬 내 원소를 정렬
+ ```ndarray.sort()```
  * 행렬 자체에서 ```sort()```를 호출하는 방식
  * 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None
  * 기본적으로 오름차순으로 행렬 내 원소를 정렬

In [27]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort( )로 정렬
sort_array1 = np.sort(org_array)
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


내림차순으로 정렬하기 위해서는
[::-1]을 적용

In [28]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행

In [30]:
array2d = np.array([[8, 12],
 [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환하기
```np.argsort()```
+ 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 를 이용
+ 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [31]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


내림차순으로 정렬 시에 원본 행렬의 인덱스를 구하는 것도 ```np.argsort( )[::-1]```

In [32]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


넘파이의 ndarray는 RDBMS의 TABLE 칼럼이
나 뒤에 소개할 판다스 DataFrame 칼럼과 같은 **메타 데이터를 가질 수 없음**  
따라서 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야 함

In [33]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적고 전치 행렬 구하기
#### 행렬 내적(행렬 곱)
+ 행렬 내적은 행렬 곱
+ 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산이 가능
+ 두 행렬 A와 B의 내적은 왼쪽 행렬의 row와 오른쪽 행렬의 column의 원소들을 순차적
으로 곱한 뒤 그 결과를 모두 더한 값

In [35]:
A = np.array( [[1, 2, 3],
 [4, 5, 6]] )
B = np.array( [[7, 8],
 [9, 10],
  [11, 12]] )
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 전치 행렬
+ 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
+ 행렬 A의 전치 행렬은 A^T와 같이 표기
+ transpose()를 이용

In [36]:
A = np.array([[1, 2],
 [3, 4]])
transpose_mat = np.transpose(A)
print ('A 의 전치 행렬:\n', transpose_mat)

A 의 전치 행렬:
 [[1 3]
 [2 4]]
