<a href="https://colab.research.google.com/github/dhyun16/ESAA/blob/main/%EA%B9%80%EB%91%90%ED%98%84_0904_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [1]:
import numpy as np

In [21]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))

In [23]:
result = np.dot(A, B)
print(result)

[[0.29899963 0.8843065 ]
 [0.35127761 1.05838323]
 [0.3104198  0.79778125]
 [0.2190997  0.64356709]
 [0.20697052 0.92389762]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
Z = np.arange(11)

Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [25]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z**Z legal  
2 << Z >> 2 legal  
Z <- Z legal  
1j*Z legal  
Z/1/1 legal  
Z<Z>Z illegal  


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_1186/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_1186/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_1186/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [27]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print("공통 값:", np.intersect1d(Z1, Z2))

공통 값: [0 2 5 6 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [28]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_1186/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

not true  
nan != i

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [29]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [30]:
A = np.ones(3, dtype=float) * 1
B = np.ones(3, dtype=float) * 2

# 1. B = A + B (B의 버퍼에 A + B 결과 저장)
np.add(A, B, out=B)

# 2. A = -A (A의 버퍼에 -A 결과 저장)
np.negative(A, out=A)

# 3. A = A / 2 (A의 버퍼에 -A / 2 결과 저장)
np.divide(A, 2, out=A)

# 4. A = A * B (A의 버퍼에 최종 결과 저장)
np.multiply(A, B, out=A)

print(A)

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [32]:
Z = np.random.uniform(0, 10, 10)
Z - Z % 1

array([8., 2., 4., 1., 4., 5., 9., 2., 0., 4.])

In [34]:
np.floor(Z)

array([8., 2., 4., 1., 4., 5., 9., 2., 0., 4.])

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [35]:
Z = np.zeros((5, 5)) + np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [37]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.11379843 0.21766286 0.37679487 0.44992369 0.67149959 0.68193678
 0.75931286 0.90318926 0.98632639 0.99802979]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [16]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
np.array_equal(A, B)

[0 0 0 1 0] [1 0 1 1 0]


False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [14]:
Z = np.random.random((10, 2))

x = Z[:, 0]
y = Z[:, 1]

r = np.sqrt(x**2 + y**2) # 거리 r 계산 (피타고라스 정리)
theta = np.arctan2(y, x)  # 각도 theta 계산 (라디안 단위)

polar = np.column_stack((r, theta)) # 2차원 행렬로 합치기

print(polar)

[[0.27970483 1.44610952]
 [0.89104819 0.32189836]
 [1.03350712 0.56702645]
 [0.57682416 0.57998274]
 [1.01262424 1.09213655]
 [0.30495572 1.48390282]
 [0.38880936 1.19019609]
 [1.03712126 0.63596068]
 [0.84470657 1.2191327 ]
 [1.22471202 0.95077094]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [13]:
Z = np.random.random(10) # 사이즈가 10인 1차원 벡터 만들기
print(Z)
Z[Z.argmax()] = 0 # argmax를 이용하여 최댓값의 인덱스를 찾고, 그 자리를 0으로 대체
print(Z)

[0.61818989 0.67834492 0.74860649 0.21507495 0.71706391 0.88031682
 0.04534994 0.14158847 0.81959762 0.16098284]
[0.61818989 0.67834492 0.74860649 0.21507495 0.71706391 0.
 0.04534994 0.14158847 0.81959762 0.16098284]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [18]:
Z = np.arange(100) # 0부터 99까지
v = np.random.uniform(0,100) # uniform distribution 따르는 무작위 실수 생성
print(Z)
print(v)
dist = (np.abs(Z-v)).argmin() # Z의 각 원소랑 v의 차이를 구하고 절댓값으로 만든 다음 가장 작은 거리의 인덱스
print(Z[dist])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
68.08189392775108
68


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [12]:
Z = np.arange(9).reshape(3,3) # 0부터 8까지 숫자로 (3,3) 2차원 배열 만들기

for index, value in np.ndenumerate(Z): #  ndenumerate함수는 인덱스, 값을 반환해주기 때문에 for문을 이용하여 순서대로 출력되도록 함
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [11]:
n = 3 # 2차원 배열의 크기
p = 2 # 값을 바꾸고 싶은 개수
Z = np.zeros((n,n)) # 0으로 채워진 배열 만들기
np.put(Z, np.random.choice(range(n*n), p, replace = False), 2) # replace = False는 중복 방지
print(Z)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [3]:
Z = np.random.randint(0,10,(3,3)) # 0부터 9 사이의 숫자가 무작위로 들어간 (3,3)
Z

array([[0, 2, 4],
       [9, 2, 9],
       [6, 4, 8]])

In [6]:
n = 0
Z[:, n]   # n번째 열 전체
order = Z[:, n].argsort()   # 예: [0, 2, 1]
Z_sorted = Z[order]   # 또는 한 줄로: Z[Z[:, n].argsort()]
print(Z_sorted)

[[0 2 4]
 [6 4 8]
 [9 2 9]]


In [7]:
n = 1
Z[:, n]   # n번째 열 전체
order = Z[:, n].argsort()   # 예: [0, 2, 1]
Z_sorted = Z[order]   # 또는 한 줄로: Z[Z[:, n].argsort()]
print(Z_sorted)

[[0 2 4]
 [9 2 9]
 [6 4 8]]


In [8]:
n = 2
Z[:, n]   # n번째 열 전체
order = Z[:, n].argsort()   # 예: [0, 2, 1]
Z_sorted = Z[order]   # 또는 한 줄로: Z[Z[:, n].argsort()]
print(Z_sorted)

[[0 2 4]
 [6 4 8]
 [9 2 9]]
